development:
  adapter: mysql2
  host: localhost
  database: votefolio_development
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  host: localhost
  database: votefolio_test
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  database: votefolio_production
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
  timeout: 5000
